import React from "react";

function Equipment(props) {
  function handleEquipment(e) {
    const { value, name } = e.target;
    props.setCharacter({
      equipment: {
        ...props.character.equipment,
        [name]: value,
      },
    });
  }

  return (
    <div>
      <h3>Death Saves</h3>
      <label>
        Successes
        <input
          type="checkbox"
          name="death_save1"
          id="death_save1"
          value="death_save1"
        />
      </label>
      <label>
        <input
          type="checkbox"
          name="death_save2"
          id="death_save2"
          value="death_save2"
        />
      </label>
      <label>
        <input
          type="checkbox"
          name="death_save3"
          id="death_save3"
          value="death_save3"
        />
      </label>
      <br />
      <label>
        Failures
        <input
          type="checkbox"
          name="death_fail1"
          id="death_fail1"
          value="death_fail1"
        />
      </label>
      <label>
        <input
          type="checkbox"
          name="death_fail2"
          id="death_fail2"
          value="death_fail2"
        />
      </label>
      <label>
        <input
          type="checkbox"
          name="death_fail3"
          id="death_fail3"
          value="death_fail3"
        />
      </label>
      <h3>Weapons/Attacks</h3>
      <table>
        <thead>
          <tr>
            <th>Weapon (Type/Range)</th>
            <th>Attack</th>
            <th>Damage</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <input
                type="text"
                name="weapon1"
                value={props.character.equipment?.weapon1}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="attack1"
                value={props.character.equipment?.attack1}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="damage1"
                value={props.character.equipment?.damage1}
                onChange={handleEquipment}
              />
            </td>
          </tr>
          <tr>
            <td>
              <input
                type="text"
                name="weapon2"
                value={props.character.equipment?.weapon2}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="attack2"
                value={props.character.equipment?.attack2}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="damage2"
                value={props.character.equipment?.damage2}
                onChange={handleEquipment}
              />
            </td>
          </tr>
          <tr>
            <td>
              <input
                type="text"
                name="weapon3"
                value={props.character.equipment?.weapon3}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="attack3"
                value={props.character.equipment?.attack3}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="damage3"
                value={props.character.equipment?.damage3}
                onChange={handleEquipment}
              />
            </td>
          </tr>
          <tr>
            <td>
              <input
                type="text"
                name="weapon4"
                value={props.character.equipment?.weapon4}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="attack4"
                value={props.character.equipment?.attack4}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="damage4"
                value={props.character.equipment?.damage4}
                onChange={handleEquipment}
              />
            </td>
          </tr>
          <tr>
            <td>
              <input
                type="text"
                name="weapon5"
                value={props.character.equipment?.weapon5}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="attack5"
                value={props.character.equipment?.attack5}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="damage5"
                value={props.character.equipment?.damage5}
                onChange={handleEquipment}
              />
            </td>
          </tr>
        </tbody>
      </table>
      <h3>Equipment</h3>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Weight</th>
            <th>Location</th>
            <th>Worth</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <input
                type="text"
                name="name1"
                value={props.character.equipment?.name1}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="weight1"
                value={props.character.equipment?.weight1}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="location1"
                value={props.character.equipment?.location1}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="worth1"
                value={props.character.equipment?.worth1}
                onChange={handleEquipment}
              />
            </td>
          </tr>
          <tr>
            <td>
              <input
                type="text"
                name="name2"
                value={props.character.equipment?.name2}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="weight2"
                value={props.character.equipment?.weight2}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="location2"
                value={props.character.equipment?.location2}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="worth2"
                value={props.character.equipment?.worth2}
                onChange={handleEquipment}
              />
            </td>
          </tr>
          <tr>
            <td>
              <input
                type="text"
                name="name3"
                value={props.character.equipment?.name3}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="weight3"
                value={props.character.equipment?.weight3}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="location3"
                value={props.character.equipment?.location3}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="worth3"
                value={props.character.equipment?.worth3}
                onChange={handleEquipment}
              />
            </td>
          </tr>
          <tr>
            <td>
              <input
                type="text"
                name="name4"
                value={props.character.equipment?.name4}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="weight4"
                value={props.character.equipment?.weight4}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="location4"
                value={props.character.equipment?.location4}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="worth4"
                value={props.character.equipment?.worth4}
                onChange={handleEquipment}
              />
            </td>
          </tr>
          <tr>
            <td>
              <input
                type="text"
                name="name5"
                value={props.character.equipment?.name5}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="weight5"
                value={props.character.equipment?.weight5}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="location5"
                value={props.character.equipment?.location5}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="worth5"
                value={props.character.equipment?.worth5}
                onChange={handleEquipment}
              />
            </td>
          </tr>
        </tbody>
      </table>
      <table>
        <thead>
          <tr>
            <th>Cp</th>
            <th>Sp</th>
            <th>Ep</th>
            <th>Gp</th>
            <th>Pp</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <input
                type="text"
                name="copper"
                value={props.character.equipment?.copper}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="silver"
                value={props.character.equipment?.silver}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="electrum"
                value={props.character.equipment?.electrum}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="gold"
                value={props.character.equipment?.gold}
                onChange={handleEquipment}
              />
            </td>
            <td>
              <input
                type="text"
                name="platinum"
                value={props.character.equipment?.platinum}
                onChange={handleEquipment}
              />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}

export default Equipment;
