import React from "react";

function Languages(props) {
  function handleLanguages(e) {
    const { value, name } = e.target;
    props.setCharacter({
      equipment: {
        ...props.character.equipment,
        [name]: value,
      },
    });
  }

  return (
    <div>
      <table>
        <thead>
          <tr>
            <th>
              <h3>Languages</h3>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <input
                type="text"
                name="language1"
                value={props.character.languages?.language1}
                onChange={handleLanguages}
              />
            </td>
            <td>
              <input
                type="text"
                name="language2"
                value={props.character.languages?.language2}
                onChange={handleLanguages}
              />
            </td>
            <td>
              <input
                type="text"
                name="language3"
                value={props.character.languages?.language3}
                onChange={handleLanguages}
              />
            </td>
          </tr>
          <tr>
            <td>
              <input
                type="text"
                name="language4"
                value={props.character.languages?.language4}
                onChange={handleLanguages}
              />
            </td>
            <td>
              <input
                type="text"
                name="language5"
                value={props.character.languages?.language5}
                onChange={handleLanguages}
              />
            </td>
            <td>
              <input
                type="text"
                name="language6"
                value={props.character.languages?.language6}
                onChange={handleLanguages}
              />
            </td>
          </tr>
          <tr>
            <td>
              <input
                type="text"
                name="language7"
                value={props.character.languages?.language7}
                onChange={handleLanguages}
              />
            </td>
            <td>
              <input
                type="text"
                name="language8"
                value={props.character.languages?.language8}
                onChange={handleLanguages}
              />
            </td>
            <td>
              <input
                type="text"
                name="language9"
                value={props.character.languages?.language9}
                onChange={handleLanguages}
              />
            </td>
          </tr>
          <tr>
            <td>
              <input
                type="text"
                name="language10"
                value={props.character.languages?.language10}
                onChange={handleLanguages}
              />
            </td>
            <td>
              <input
                type="text"
                name="language11"
                value={props.character.languages?.language11}
                onChange={handleLanguages}
              />
            </td>
            <td>
              <input
                type="text"
                name="language12"
                value={props.character.languages?.language12}
                onChange={handleLanguages}
              />
            </td>
          </tr>
          <tr>
            <td>
              <input
                type="text"
                name="language13"
                value={props.character.languages?.language13}
                onChange={handleLanguages}
              />
            </td>
            <td>
              <input
                type="text"
                name="language14"
                value={props.character.languages?.language14}
                onChange={handleLanguages}
              />
            </td>
            <td>
              <input
                type="text"
                name="language15"
                value={props.character.languages?.language15}
                onChange={handleLanguages}
              />
            </td>
          </tr>
          <tr>
            <td>
              <input
                type="text"
                name="language16"
                value={props.character.languages?.language16}
                onChange={handleLanguages}
              />
            </td>
            <td>
              <input
                type="text"
                name="language17"
                value={props.character.languages?.language17}
                onChange={handleLanguages}
              />
            </td>
            <td>
              <input
                type="text"
                name="language18"
                value={props.character.languages?.language18}
                onChange={handleLanguages}
              />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}
export default Languages;
